name: Update Snapshots
on:
  pull_request:
    branches: [main]
jobs:
  update-snapshots:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      # Install dependencies and build CLI app
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Build Project
        run: pnpm run build

      # Nextjs
      - name: Build Nextjs
        run: pnpm build:nextjs
      - name: Test Nextjs
        run: pnpm test:nextjs
        env:
          COMMAND: "pnpm run:nextjs"

      # React
      - name: Build React
        run: pnpm build:react
      - name: Test React
        run: pnpm test:react
        env:
          COMMAND: "pnpm run:react"
          PORT: 5173

      # Vue
      - name: Build Vue
        run: pnpm build:vue
      - name: Test Vue
        run: pnpm test:vue
        env:
          COMMAND: "pnpm run:vue"
          PORT: 5173

      # Preact
      - name: Build Preact
        run: pnpm build:preact
      - name: Test Preact
        run: pnpm test:preact
        env:
          COMMAND: "pnpm run:preact"
          PORT: 5173

      # Svelte
      - name: Build Svelte
        run: pnpm build:svelte
      - name: Test Svelte
        run: pnpm test:svelte
        env:
          COMMAND: "pnpm run:svelte"
          PORT: 5173

      # Vanilla
      - name: Build Vanilla
        run: pnpm build:vanilla
      - name: Test Vanilla
        run: pnpm test:vanilla
        env:
          COMMAND: "pnpm run:vanilla"
          PORT: 5173

      # Upload Test Results
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30a

      # Commit snapshot changes
      - uses: EndBug/add-and-commit@v9
        with:
          message: "[CI] Update snapshots"
