name: Playwright Tests
on:
  push:
    branches: [feat/e2e-tests]
  # pull_request:
  #   branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Build Project
        run: pnpm run build
      - name: Build Nextjs
        run: pnpm build:nextjs
      - name: Test Nextjs
        run: pnpm test:nextjs
        env:
          COMMAND: "cd dist/nextjs && yarn dev"
      - name: Build React
        run: pnpm build:react
      - name: Test React
        run: pnpm test:react
        env:
          COMMAND: "cd dist/react && yarn dev"
          PORT: 5173
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30a
      - uses: EndBug/add-and-commit@v9
        with:
          message: "[CI] Update snapshots"
